Allow retrieving the default admin password with actions
canonical/grafana-operator pull request #41
Opened 2021-10-29 22:30 UTC by rbarry82

2021-10-29 22:34 UTC, rbarry82 commented
Rebased on top of the lzma patch...

2021-10-30 06:46 UTC, mmanciop requested changes
Needs some docu about the way the password works in the README and improving the description in actions.yaml then can be merged

2021-10-30 06:46 UTC, mmanciop commented on actions.yaml
> +get-admin-password:
Retrieve the current password for the “admin” account in Grafana

2021-11-01 09:53 UTC, simskij commented on src/charm.py
> +        return "".join(secrets.choice(chars) for _ in range(12))
I get the point about not using non ascii/digit letters, but why limit ourselves to twelve positions? Seems like we could use way longer default passwords to increase the entropy greatly.

2021-11-01 09:53 UTC, simskij commented on actions.yaml
> +get-admin-password:
@mmanciop I'm a little bit opposed to this from a security standpoint. It should only get the *initial* password, right? If the user changes the password, the expected behavior, from my point of view, would be that it becomes non-retrievable (but maybe resettable through an action).

2021-11-01 15:56 UTC, jnsgruk commented on actions.yaml
> +get-admin-password:
Agreed

2021-11-01 23:09 UTC, rbarry82 commented on src/charm.py
> +        return "".join(secrets.choice(chars) for _ in range(12))
Basically because it exceeds the baseline for PCI-DSS, ISO2700[12], and NIST 800-63. 

We could certainly add more characters, but considering that a change is required anyway, meeting baseline security requirements for every major framework is hopefully sufficient.

2021-11-01 23:43 UTC, rbarry82 commented on actions.yaml
> +get-admin-password:
Do we want to make it resettable via an action? This can be done with `grafana-cli` in the workload container, but I'm not knowledgeable enough about Juju's RBAC model to guess whether letting Juju admins reset admin passwords for deployed workloads iss sane or not.

2021-11-03 19:11 UTC, mmanciop commented
@simskij i think having for now the admin password generated by The charmed operator, retrievable via action and not yet modifiable via juju apis to be a good enough stopgap until Juju secrets land.

2021-11-03 20:38 UTC, simskij commented
> @simskij i think having for now the admin password generated by The charmed operator, retrievable via action and not yet modifiable via juju apis to be a good enough stopgap until Juju secrets land.

I agree! My main point is that user-changed passwords never should be retrievable.

2021-11-04 11:19 UTC, rbarry82 commented
@simskij @mmanciop if we're agreed, let's see some :+1:s!

2021-11-04 12:05 UTC, mmanciop approved these changes

2021-11-04 19:39 UTC, simskij approved these changes

2021-11-16 10:35 UTC, mmanciop commented
@rbarry82 what is preventing us from squashing, merging and publishing a new `edge`?

2021-11-16 12:16 UTC, rbarry82 commented
Only that I missed the github notification about the second approval

2021-11-16 12:17 UTC, merged

2021-11-16 12:20 UTC, mmanciop commented
@rbarry82 I really wish we would use more the "Squash and merge". What is the value to have a commit with message "Linters" in the `main` branch? :-(

2021-11-16 12:41 UTC, rbarry82 commented
I really don't have a strong preference on it, but there's no shortage of opinions titled "Squash merge considered harmful" ;)

2021-11-16 12:45 UTC, mmanciop commented
If the overall PR changeset is huge, I even agree. But then, if the sequence of commits is an intended artifact we wish to preserve, you gotta force-push edits to the PR where the linting is applied where it matters and I shall not complain :D